// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"game-custom-com/internal/dao/internal"
)

// internalCollectDao is internal type for wrapping internal DAO implements.
type internalCollectDao = *internal.CollectDao

// collectDao is the data access object for table collect.
// You can define custom methods on it to extend its functionality as you wish.
type collectDao struct {
	internalCollectDao
}

var (
	// Collect is globally public accessible object for table collect operations.
	Collect = collectDao{
		internal.NewCollectDao(),
	}
)

// Fill with you ideas below.
