// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"game-custom-com/internal/dao/internal"
)

// internalErrorDao is internal type for wrapping internal DAO implements.
type internalErrorDao = *internal.ErrorDao

// errorDao is the data access object for table error.
// You can define custom methods on it to extend its functionality as you wish.
type errorDao struct {
	internalErrorDao
}

var (
	// Error is globally public accessible object for table error operations.
	Error = errorDao{
		internal.NewErrorDao(),
	}
)

// Fill with you ideas below.
