// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"game-custom-com/internal/dao/internal"
)

// internalFollowDao is internal type for wrapping internal DAO implements.
type internalFollowDao = *internal.FollowDao

// followDao is the data access object for table follow.
// You can define custom methods on it to extend its functionality as you wish.
type followDao struct {
	internalFollowDao
}

var (
	// Follow is globally public accessible object for table follow operations.
	Follow = followDao{
		internal.NewFollowDao(),
	}
)

// Fill with you ideas below.
