// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"game-custom-com/internal/dao/internal"
)

// internalLikeDao is internal type for wrapping internal DAO implements.
type internalLikeDao = *internal.LikeDao

// likeDao is the data access object for table like.
// You can define custom methods on it to extend its functionality as you wish.
type likeDao struct {
	internalLikeDao
}

var (
	// Like is globally public accessible object for table like operations.
	Like = likeDao{
		internal.NewLikeDao(),
	}
)

// Fill with you ideas below.
