// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"game-custom-com/internal/dao/internal"
)

// internalSearchHistoryDao is internal type for wrapping internal DAO implements.
type internalSearchHistoryDao = *internal.SearchHistoryDao

// searchHistoryDao is the data access object for table search_history.
// You can define custom methods on it to extend its functionality as you wish.
type searchHistoryDao struct {
	internalSearchHistoryDao
}

var (
	// SearchHistory is globally public accessible object for table search_history operations.
	SearchHistory = searchHistoryDao{
		internal.NewSearchHistoryDao(),
	}
)

// Fill with you ideas below.
