// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"game-custom-com/internal/dao/internal"
)

// internalSectionDao is internal type for wrapping internal DAO implements.
type internalSectionDao = *internal.SectionDao

// sectionDao is the data access object for table section.
// You can define custom methods on it to extend its functionality as you wish.
type sectionDao struct {
	internalSectionDao
}

var (
	// Section is globally public accessible object for table section operations.
	Section = sectionDao{
		internal.NewSectionDao(),
	}
)

// Fill with you ideas below.
