// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"game-custom-com/internal/dao/internal"
)

// internalVisitDataDao is internal type for wrapping internal DAO implements.
type internalVisitDataDao = *internal.VisitDataDao

// visitDataDao is the data access object for table visit_data.
// You can define custom methods on it to extend its functionality as you wish.
type visitDataDao struct {
	internalVisitDataDao
}

var (
	// VisitData is globally public accessible object for table visit_data operations.
	VisitData = visitDataDao{
		internal.NewVisitDataDao(),
	}
)

// Fill with you ideas below.
